// try catch and throw

function d(a,b) {
    try{
        if(b === 0){
            throw new Error("Can't devide by 0")
        }
        else{
            return a/b;
        }
    }
    catch(err){
        c
    }
}